import React from "react";
import { Link } from "react-router-dom";
const token = localStorage.getItem('token');

const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <h1>Token:</h1>
      <p>{token}</p>

      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/HomePage" style={{ color: "#87CEFA", textDecoration: "none" }}>
          HomePage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/login" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Homeopen
            </Link>
          <Link to="/" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Landingpage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/register" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Register
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/home1" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Home1
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/world" style={{ color: "#87CEFA", textDecoration: "none" }}>
            World
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/home2" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Home2
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/loading" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Loading
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/itemcreator" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ItemCreator
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/home3" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Home3
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/pedia" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Pedia
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/post" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Post
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/store" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Store
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
